version: '3.0'

services:
  ocserv:
    image: fkia-ocserv:latest
    build: .
    restart: always
    container_name: fkia-ocserv
    privileged: true
    # hostname: <domain>
    volumes:
      - "./ocserv:/etc/ocserv/:ro"
